# Usa una imagen de Java 17
FROM eclipse-temurin:17-jdk-alpine

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el JAR generado al contenedor
COPY target/integradortp2-0.0.1-SNAPSHOT.jar app.jar

# Expone el puerto 8080
EXPOSE 8080C:\Users\Electro-Hard\Documents\tu-repositorio\tpIntegrador\...

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "app.jar"]
